pockets:
  default:
    # Generic default pocket - replace with actual coordinates
    center_x: 0.0
    center_y: 0.0
    center_z: 0.0
    size_x: 20.0
    size_y: 20.0
    size_z: 20.0

  GyrA_pocket:
    # DNA gyrase (topoisomerase II) Ciprofloxacin-binding pocket
    # Reference: PDB 2XCT (S. aureus Gyrase + Ciprofloxacin, 3.35 Ã… resolution)
    # CPF center extracted from ligand coordinates
    center_x: 2.822
    center_y: 43.729
    center_z: 68.710
    size_x: 6.0
    size_y: 10.0
    size_z: 15.0

  GyrA_D87_pocket:
    # Pocket focused on D87 residue for mutation studies
    center_x: 10.8
    center_y: 21.1
    center_z: 16.2
    size_x: 20.0
    size_y: 20.0
    size_z: 20.0

  RpoB_pocket:
    # M. tuberculosis RNA Polymerase beta subunit Rifampicin-binding pocket
    # Reference: PDB 5UH6 (M. tuberculosis RpoB + Rifampicin)
    # RFP center extracted from ligand coordinates (Chain C, Res 1201)
    # Resistance mutation: S456L (steric clash mechanism)
    center_x: -10.157
    center_y: 0.335
    center_z: 19.853
    size_x: 17.0
    size_y: 19.0
    size_z: 21.0
